webdetails/cda

cda-pentaho-base/resources/previewer/previewer.css, cda-pentaho-base/resources/previewer/previewer.html, cda-pentaho-base/resources/previewer/previewer.js
=> [CDA-123] Have feedback when there's error. Or just don't lock the previewer

cda-core/src/pt/webdetails/cda/CdaEngine.java, cda-core/src/pt/webdetails/cda/exporter/AbstractExporter.java, cda-core/src/pt/webdetails/cda/exporter/AbstractKettleExporter.java, cda-core/src/pt/webdetails/cda/exporter/BinaryExporter.java, cda-core/src/pt/webdetails/cda/exporter/DefaultStreamExporter.java, cda-core/src/pt/webdetails/cda/exporter/ExportOptions.java, cda-core/src/pt/webdetails/cda/exporter/ExportedQueryResult.java, cda-core/src/pt/webdetails/cda/exporter/ExportedStreamQueryResult.java, cda-core/src/pt/webdetails/cda/exporter/ExportedTableQueryResult.java, cda-core/src/pt/webdetails/cda/exporter/Exporter.java, cda-core/src/pt/webdetails/cda/exporter/ExporterEngine.java, cda-core/src/pt/webdetails/cda/exporter/ExporterException.java, cda-core/src/pt/webdetails/cda/exporter/HtmlExporter.java, cda-core/src/pt/webdetails/cda/exporter/JsonExporter.java, cda-core/src/pt/webdetails/cda/exporter/StreamExporter.java, cda-core/src/pt/webdetails/cda/exporter/TableExporter.java, cda-core/src/pt/webdetails/cda/exporter/UnsupportedExporterException.java, cda-core/src/pt/webdetails/cda/exporter/XlsExporter.java, cda-core/src/pt/webdetails/cda/exporter/XmlExporter.java, cda-core/src/pt/webdetails/cda/query/IQueryArguments.java, cda-core/src/pt/webdetails/cda/query/QueryOptions.java
=> [CDA-124] Exporting to .xls empty parameters results in 500 error

cda-core/src/pt/webdetails/cda/dataaccess/SimpleDataAccess.java
=> [CDE-443] Expose CDA extra cache keys in CDE editor

cda-core/src/pt/webdetails/cda/exporter/JsonExporter.java, cda-core/test-resources/repository/sample-output.cda, cda-core/test-src/pt/webdetails/cda/tests/OutputTest.java, cda-pentaho-base/resources/previewer/previewer.js
=> [CDA-127] Deal with invalid numbers, such as 0/0

cda-core/src/pt/webdetails/cda/utils/TableModelUtils.java
=> [CDA-122] When we use the "Columns" property, we need to clear the CDA Cache

cda-core/src/pt/webdetails/cda/utils/TableModelUtils.java
=> [CDA-122] fixed bug causing CompoundJoinTest to fail

cda-core/src/pt/webdetails/cda/dataaccess/JsonScriptableDataAccess.java, cda-core/test-resources/repository/sample-json-scripting.cda
@pamval @diogofscmariano please review
=> [CDA-130] Scriptable JSON data source: null values not supported

cda-pentaho-base/resources/fileEditor/editor.html, cda-pentaho-base/resources/previewer/languages/Messages.properties, cda-pentaho-base/resources/previewer/languages/Messages_es.properties, cda-pentaho-base/resources/previewer/languages/Messages_es_MX.properties, cda-pentaho-base/resources/previewer/languages/Messages_fr.properties, cda-pentaho-base/resources/previewer/languages/Messages_hr.properties, cda-pentaho-base/resources/previewer/previewer.html
=> [CDA-139] Cda file edtior and cda previewer are not working in IE8

cda-pentaho-base/resources/cachemanager/cache.html
=> [CDA-140] CDA Cache Manager always display version label as TRUNK-SNAPSHOT

cda-core/src/pt/webdetails/cda/exporter/DefaultStreamExporter.java
=> [CDA-144] Exporting does not work when String array parameter is empty

cda-core/res/ehcache-cda.xml, cda-core/res/ehcache.xml, cda-pentaho/resources/ehcache-cda.xml, cda-pentaho5/resources/ehcache-cda.xml
=> [CDA-143] CDA cache is not cleared when restarting the server

cda-pentaho-base/resources/previewer/previewer.html, cda-pentaho-base/resources/previewer/previewer.js
=> [CDA-147] When a query with parameter fails the parameter boxes are not shown

cda-pentaho-base/resources/previewer/previewer.js
=> [CDA-150] Refresh button is not showing

cda-core/build.properties, cda-core/ivy.xml
- also moved all spring revisions to build.properties
=> spring.framework upgraded to 3.2.14.RELEASE

cda-core/build.properties, cda-core/ivy.xml
with those maintained by the build team.
@lucboudreau @lgrill-pentaho @pamval
=> [CLEANUP] making version properties consistent

cda-core/src/pt/webdetails/cda/formula/CdaSecurityParameterProvider.java, cda-core/src/pt/webdetails/cda/formula/CdaSessionParameterProvider.java, cda-core/src/pt/webdetails/cda/formula/CdaSystemParameterProvider.java, cda-core/src/pt/webdetails/cda/formula/DefaultSessionFormulaContext.java, cda-core/test-src/pt/webdetails/cda/formula/CdaSecurityParameterProviderTest.java, cda-core/test-src/pt/webdetails/cda/formula/CdaSessionParameterProviderTest.java, cda-core/test-src/pt/webdetails/cda/formula/CdaSystemParameterProviderTest.java, cda-core/test-src/pt/webdetails/cda/formula/DefaultSessionFormulaContextTest.java, cda-core/test-src/pt/webdetails/cda/utils/NaturalOrderTest.java, cda-core/test-src/pt/webdetails/cda/utils/ParameterArrayToStringEncoderTest.java, cda-core/test-src/pt/webdetails/cda/utils/ParameterTest.java, cda-core/test-src/pt/webdetails/cda/utils/PathRelativizerTest.java
[TEST]
- Added unit tests for pt.webdetails.cda.formula package
- Moved pt.webdetails.cda.utils tests to correct package
- Fixed issue with CdaSystemParameterProviderTest on getParameter
[CLEANUP]
- Applied check style to pt.webdetails.cda.formula classes
- Updated license headers
=> [TEST] + [CLEANUP] formula package

cda-core/src/pt/webdetails/cda/connections/AbstractConnection.java, cda-core/src/pt/webdetails/cda/connections/DummyConnection.java, cda-core/src/pt/webdetails/cda/connections/JndiConnectionInfo.java, cda-core/test-src/pt/webdetails/cda/connections/DummyConnectionTest.java, cda-core/test-src/pt/webdetails/cda/connections/JndiConnectionInfoTest.java
=> Unit tests for AbstractConnection and JndiConnectionInfo

cda-core/build.xml
=> [TEST] - Fix jacoco integration test classpath

pentaho/pom.xml, pom.xml
=> [CLEANUP] - Updating cpf version due to artefact cleanup

assemblies/cda-disabled/src/assembly/descriptors/assembly.xml, assemblies/cda-samples/src/assembly/descriptors/assembly.xml, assemblies/cda/src/assembly/descriptors/assembly.xml
- Reviewed zip directory name
@pamval please review
=> [ENGOPS-1529]

core/src/test/java/pt/webdetails/cda/exporter/XmlExporterTest.java
@diogofscmariano @pamval please review
=> [TEST] force tz for XmlExporterTest

core/src/main/java/pt/webdetails/cda/utils/CalculatedTableModel.java, core/src/test/java/pt/webdetails/cda/utils/CalculatedTableModelTest.java
=> [CDA-160] Returning null when CalculatedColumns fails to evaluate formula

pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/previewer/previewer.css, pentaho/src/main/resources/previewer/previewer.html, pentaho/src/main/resources/previewer/previewer.js, pentaho/src/main/resources/static/about.html
@pamval should I send a request to UX to review the style in this issue? please review
=> [CDA-92] Add type validation to parameter input forms in CDA previewer

core/src/main/java/pt/webdetails/cda/dataaccess/CompoundDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/JoinCompoundDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/UnionCompoundDataAccess.java
- Allow configuring calculated columns when creating Join/Union compound queries in the CDE editor
=> [CDA-104] Calculated Column at Compound Queries

cda-core/src/pt/webdetails/cda/dataaccess/CompoundDataAccess.java, cda-core/src/pt/webdetails/cda/dataaccess/JoinCompoundDataAccess.java, cda-core/src/pt/webdetails/cda/dataaccess/UnionCompoundDataAccess.java, cda-core/src/pt/webdetails/cda/utils/CalculatedTableModel.java, cda-core/test-resources/repository/sample-scripting.cda, cda-core/test-src/pt/webdetails/cda/tests/CalculatedTableModelTest.java, cda-pentaho-base/resources/previewer/previewer.css, cda-pentaho-base/resources/previewer/previewer.html, cda-pentaho-base/resources/previewer/previewer.js, cda-pentaho-base/resources/static/about.html, cda-pentaho5/solution/bi-developers/cda/template.html
=> cherry-picks from master

.gitignore, cda-core/src/pt/webdetails/cda/dataaccess/CompoundDataAccess.java, cda-core/src/pt/webdetails/cda/dataaccess/JoinCompoundDataAccess.java, cda-core/src/pt/webdetails/cda/dataaccess/UnionCompoundDataAccess.java, cda-core/src/pt/webdetails/cda/utils/CalculatedTableModel.java, cda-pentaho-base/resources/previewer/previewer.html
=> [CHERRYPICK][CDA-92][CLEANUP] Fixed focus event on output index box

pentaho/src/main/resources/previewer/previewer.css, pentaho/src/main/resources/previewer/previewer.js
=> [CDA-169] CSS improvements in CDA Previewer

assemblies/src/main/resources/marketplace.xml, pentaho/src/main/resources/version.xml
=> [CLEANUP] - Updating project version reference

core/src/main/java/pt/webdetails/cda/dataaccess/JoinCompoundDataAccess.java, core/src/test/java/pt/webdetails/cda/filetests/CompoundQueryTest.java, core/src/test/resources/repository/sample-join.cda
=> [CDA-171] Using a Compound Join datasource the join is case insensitive

core/src/test/resources/repository/sample-join.cda
Didn't catch this earlier because the local build didn't fail when this test also failed. 
@pamval please review
=> [CDA-171] Fixed sample-join.cda tag names and also added missing tags

pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/test/java/pt/webdetails/cda/CdaUtilsTest.java
- encode input parameter to avoid injections
@pamval, review it please or re-tag someone appropriate (`cda` is not mentioned in our cheat list). Also, if you know better fix, please do not hesitate to point it out :smile:
=> [PPP-3463] - Reflected Cross-Site (XSS) Scripting

cda-pentaho5/ivy.xml, cda-pentaho5/src/pt/webdetails/cda/CdaUtils.java, cda-pentaho5/test-src/pt/webdetails/cda/CdaUtilsTest.java
- check whether the input path exists and if it does, throw an exception
- add simple tests
- include `net.htmlparser.jericho` into `test` configuration
@tgf, review it please. This is a backport of https://github.com/webdetails/cda/pull/194
=> [SP-2360] - Backport of PPP-3463 - Reflected Cross-Site (XSS) Scripting (5.4 Suite)

cda-pentaho5/ivy.xml, cda-pentaho5/src/pt/webdetails/cda/CdaUtils.java, cda-pentaho5/test-src/pt/webdetails/cda/CdaUtilsTest.java
- check whether the input path exists and if it does, throw an exception
- add simple tests
@tgf, review it please. This is a backport of https://github.com/webdetails/cda/pull/194
=> [SP-2359] - Backport of PPP-3463 - Reflected Cross-Site (XSS) Scripting (6.0 Suite)

core/src/main/java/pt/webdetails/cda/connections/ConnectionCatalog.java, pentaho/src/main/java/pt/webdetails/cda/CdaFileMetaProvider.java
@pamval, @mbatchelor, could you please take a look? 
*should be merged not earlier than: https://github.com/webdetails/cpf/pull/99
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

pentaho/src/main/resources/cachemanager/cache.css, pentaho/src/main/resources/fileEditor/editor.css, pentaho/src/main/resources/static/blueprint/screen.css, pentaho/src/main/resources/static/cda.css
@pamval @pedrofvteixeira @smaring please take a look
=> [CDE-871]-Avoid hardcoding a protocol

assemblies/pom.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
=> [ENGOPS-2639] json GAV change

core/pom.xml, pentaho/pom.xml, pom.xml
TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.
=> [BACKLOG-12334] GAV changes for reporting

assemblies/pom.xml, core/pom.xml, pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-13199] GAV change for kettle5-log4j-plugin

pom.xml
@pamval  Fixes checkstyle reports picking up the wrong configuration
=> [CLEANUP] Removing deprecated report configuration

core/src/main/java/pt/webdetails/cda/ICdaEnvironment.java, core/src/test/java/pt/webdetails/cda/filetests/CdaTestEnvironment.java, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/main/java/pt/webdetails/cda/PentahoBaseCdaEnvironment.java, pentaho/src/main/java/pt/webdetails/cda/utils/Messages.java, pentaho/src/main/resources/messages.properties
- permission check was added
- internationalization support was added
=> [CDA-215] Users without 'Create Content' permission is able to edit CDA files

pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/fileEditor/editor-cde.html, pentaho/src/main/resources/fileEditor/editor.html, pentaho/src/main/resources/previewer/previewer.html, pentaho/src/main/resources/solution/bi-developers/cda/template.html, pentaho/src/main/resources/static/about.html
@pamval @plagoa @joaormf @francisco-guilherme Please review
=> [BACKLOG-19153] - Update the links and mail references.

core/src/main/java/pt/webdetails/cda/ICdaEnvironment.java, core/src/test/java/pt/webdetails/cda/filetests/CdaTestEnvironment.java, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/main/java/pt/webdetails/cda/PentahoBaseCdaEnvironment.java, pentaho/src/main/java/pt/webdetails/cda/utils/Messages.java, pentaho/src/main/resources/messages.properties
=> [SP-3809] Backport of CDA-215 - Users without 'Create Content' permission is able to edit CDA files (7.1 Suite)

core/pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
=> [BACKLOG-13306] GAV change

pentaho/pom.xml
Depends on https://github.com/pentaho/pentaho-reportwizard-core/pull/10/
=> [BACKLOG-13972] Downstream updates

core/src/main/java/pt/webdetails/cda/dataaccess/DataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/PREDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/xml/DomVisitor.java, core/src/test/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccessTest.java, core/src/test/resources/repository/sample-streaming-dataservice.cda
Reverts webdetails/cda#250
there's a build ordering issue with BACKLOG-21553 ... please consult with buildteam
=> Revert "[BACKLOG-21553] - adding streaming parameters (windowRowSize, windowR…"

core/pom.xml, pom.xml
@lgrill-pentaho @emartin-pentaho
=> [BACKLOG-22034] fix version names

core/src/main/java/pt/webdetails/cda/dataaccess/DataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/SimpleDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/xml/DomVisitor.java, core/src/test/java/pt/webdetails/cda/dataaccess/DataservicesDataAccessTest.java, core/src/test/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccessTest.java, core/src/test/java/pt/webdetails/cda/xml/DomVisitorTest.java, core/src/test/resources/repository/sample-dataservice.cda, core/src/test/resources/repository/sample-streaming-dataservice.cda
@plagoa @marcoslarsen @francisco-guilherme please review
=> [BACKLOG-22395] Default SQL query on a CDE dataservice datasource

core/src/main/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/utils/streaming/SQLStreamingReportDataFactory.java, core/src/main/java/pt/webdetails/cda/xml/DomVisitor.java, core/src/test/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccessTest.java, core/src/test/java/pt/webdetails/cda/utils/streaming/SQLStreamingReportDataFactoryTest.java, core/src/test/java/pt/webdetails/cda/xml/DomVisitorTest.java, core/src/test/resources/repository/sample-streaming-dataservice.cda
dataservices, for row and time based windows.
@pentaho/kashyyyk Please review.
Depends on https://github.com/pentaho/pdi-dataservice-plugin/pull/156
=> [BACKLOG-22231] - Control window streaming parameters in streaming

assemblies/cda-disabled/src/assembly/descriptors/assembly.xml, assemblies/cda/src/assembly/descriptors/assembly.xml
@webdetails/bobafett please review
=> [BACKLOG-25402] - CDA-proxy module included incorrectly in the platform

core/src/main/java/pt/webdetails/cda/endpoints/RestEndpoint.java, core/src/main/java/pt/webdetails/cda/exporter/ExportedQueryResult.java, core/src/main/java/pt/webdetails/cda/utils/DoQueryParameters.java
@webdetails/millenniumfalcon please review
=> [BACKLOG-25261] RestEndpoint refactor to return Responses instead of void

osgi/pom.xml, pom.xml
@pentaho/millenniumfalcon please review.
=> [CLEANUP] Fix pentaho dependency version

core/src/main/java/pt/webdetails/cda/endpoints/RestEndpoint.java, core/src/test/java/pt/webdetails/cda/endpoints/RestEndpointTest.java
@webdetails/millenniumfalcon please review
=> [BACKLOG-25482][CLEANUP] Removed redundant methods from RestEndpoint

core/src/main/java/pt/webdetails/cda/CdaInfo.java, core/src/main/java/pt/webdetails/cda/endpoints/RestEndpoint.java, core/src/main/java/pt/webdetails/cda/utils/DoQueryParameters.java, core/src/test/java/pt/webdetails/cda/endpoints/RestEndpointTest.java
@webdetails/millenniumfalcon please review
=> [CLEANUP][BACKLOG-25122] Fix POST doQuery endpoint not receiving some parameters

pentaho/src/main/resources/fileEditor/languages/Messages_zh_CN.properties, pentaho/src/main/resources/previewer/languages/Messages_zh_CN.properties
@webdetails/millenniumfalcon please review
=> Backlog 25043 - Added Simplified Chinese localization

assemblies/platform/pom.xml, core/src/main/java/pt/webdetails/cda/push/WebsocketJsonQueryEndpoint.java, core/src/main/java/pt/webdetails/cda/utils/QueryParameters.java, core/src/test/java/pt/webdetails/cda/push/WebsocketJsonQueryEndpointTest.java, core/src/test/java/pt/webdetails/cda/utils/QueryParametersTest.java, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryMessageHandler.java, pentaho/src/test/java/pt/webdetails/cda/CdaUtilsTest.java
@tgf @marcoslarsen @JoaoRPF @plagoa @graimundo please review
=> [BACKLOG-25403] Remove the javax.ws.rs-api dependency

core/pom.xml, core/src/main/java/pt/webdetails/cda/cache/DataAccessCacheElementParser.java, core/src/main/java/pt/webdetails/cda/dataaccess/AbstractDataAccess.java, core/src/main/java/pt/webdetails/cda/settings/CdaSettings.java, core/src/main/java/pt/webdetails/cda/utils/Util.java, core/src/test/java/pt/webdetails/cda/exporter/XmlExporterTest.java, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

core/src/main/java/pt/webdetails/cda/push/IWebsocketEndpoint.java, osgi/src/main/java/org/pentaho/ctools/cda/endpoints/CdaJettyWebsocket.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryMessageHandler.java
@pamval please review
@marcoslarsen FYI
=> [BACKLOG-26349] Handle close message created from error conditions

pentaho/src/main/resources/fileEditor/editor.html
*Changed formula for height calculation.
@pamval , @pentaho-lmartins , @mbatchelor Please review and merge if it's all ok. Thanks!
=> [CDA-224] - Unable to edit CDA file

pentaho/src/main/resources/fileEditor/editor.html
Cherry pick of https://github.com/webdetails/cda/pull/295/files
@ppatricio @RPAraujo
=> [SP-4829] - Backport of CDA-224 - Unable to edit CDA file (8.2 Suite)

core/src/main/java/pt/webdetails/cda/settings/CdaFileResourceLoader.java
Context at https://jira.pentaho.com/browse/CDA-232?focusedCommentId=361108#comment-361108
@mbatchelor @pamval @nantunes
=> [CDA-232] CDA streams are not properly closed

core/pom.xml
=> [BACKLOG-27566] Centralize SLF4J dependency

assemblies/cda-foundry/pom.xml, assemblies/feature/src/main/feature/feature.xml, pom.xml
[BACKLOG-27565] Centralize CXF version
[BACKLOG-27577] Centralize karaf dependencies management
[BACKLOG-27578] Use parent pom centralized profile for feature generation
@graimundo
=> [BACKLOG-27565] Centralize CXF version

core/src/main/java/pt/webdetails/cda/settings/CdaFileResourceLoader.java
=> [SP-4972] [CDA-232] CDA streams are not properly closed

pentaho/src/main/resources/fileEditor/editor.html
=> [Sp-4988] [CDA-230] - Fixed Layout problem on Firefox, CDA editor window with incorrect width

core/src/main/java/pt/webdetails/cda/settings/CdaFileResourceLoader.java
=> [SP-4971] [CDA-232] CDA streams are not properly closed

assemblies/platform/pom.xml, osgi/pom.xml, pom.xml
See: https://github.com/pentaho/maven-parent-poms/pull/117
@ricardosilva88 @RPAraujo
=> [PPP-4335] Upgrading com.fasterxml.jackson to 2.9.8

pentaho/src/main/java/pt/webdetails/cda/services/CacheManager.java, pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/cachemanager/cache.js, pentaho/src/main/resources/cachemanager/languages/Messages.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en_US.properties
@pentaho-lmartins @tgf 
please review
=> [CDA-234] - CDA page not translated

pentaho/src/main/java/pt/webdetails/cda/services/CacheManager.java, pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/cachemanager/cache.js, pentaho/src/main/resources/cachemanager/languages/Messages.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en_US.properties
@pentaho-lmartins @LeonardoCoelho71950
=> [SP-5137] [CDA-234] - CDA page not translated

pentaho/src/main/java/pt/webdetails/cda/services/CacheManager.java, pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/cachemanager/cache.js, pentaho/src/main/resources/cachemanager/languages/Messages.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en.properties, pentaho/src/main/resources/cachemanager/languages/Messages_en_US.properties
@pentaho-lmartins @LeonardoCoelho71950
=> [SP-5136] Backport of CDA-234 - CDA page not translated (7.1 Suite)

pentaho/src/main/resources/previewer/fg-menu/fg.menu.js, pentaho/src/main/resources/previewer/previewer.js
@pentaho-lmartins @dcleao please review
=> [PPP-4008] - Fix calls to discontinued functions/properties

pentaho/src/main/resources/static/theme/cupertino/jquery-ui-1.10.4.custom.css
**Attention: This is the outcome of an automated process!**
Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Webdetails/cda/commit/b55ecc04276bdaff7fc9a6b08363aa0b8f2f3668
=> [SP-5351] Backport of CDE-1029 - CDE - Datasources Panel layout - XPATH Queries not selected (8.3 Suite)

pentaho/src/main/java/pt/webdetails/cda/CdaContentGenerator.java
@bennychow please review
/cc @jcarneirohv
=> [BISERVER-5014] Setting instanceId in CdaContentGenerator

core/src/main/java/pt/webdetails/cda/dataaccess/JsonScriptableDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/ScriptableDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/SimpleDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/StreamingDataservicesDataAccess.java, core/src/main/java/pt/webdetails/cda/dataaccess/kettle/SQLKettleAdapter.java, core/src/main/java/pt/webdetails/cda/push/WebsocketJsonQueryEndpoint.java, pentaho/src/main/java/pt/webdetails/cda/CdaContentGenerator.java, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryEndpoint.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryMessageHandler.java, pentaho/src/main/java/pt/webdetails/cda/push/PentahoContext.java, pentaho/src/main/java/pt/webdetails/cda/push/PentahoEndpointConfigurationHelper.java, pentaho/src/main/java/pt/webdetails/cda/utils/AuditHelper.java
@bennychow please review
/cc @jcarneirohv
- Also, added Auditing to the web socket Push Query endpoint, which was not being audited
Depends on https://github.com/pentaho/pentaho-platform/pull/4789 to compile.
=> [BISERVER-5014] Added logging to all CDA queries to support MDC even in the face of caching

pentaho/src/main/resources/cachemanager/cache.html, pentaho/src/main/resources/fileEditor/editor-cde.html, pentaho/src/main/resources/fileEditor/editor.html, pentaho/src/main/resources/previewer/previewer.html, pentaho/src/main/resources/solution/bi-developers/cda/template.html, pentaho/src/main/resources/static/about.html
@rmansoor 
@smmribeiro @bcostahitachivantara
=> [CDE-1060] CDE links with a no longer existing URL

core/src/test/resources/classic-engine.properties
This commit is a cherry-pick from master 24c60c5bbb886f
=> [BISERVER-14599] Add PRD config file to fix unit tests.

core/src/test/resources/classic-engine.properties
@smmribeiro 
@ssamora 
@renato-s
=> [CUST-259] - Requesting a CUST for the Critical Flaws Uncovered in Pentaho (v9.0.0.7)

core/pom.xml, pom.xml
=> [PPP-4936] - upgrading the vulnerable component guava version to 32.1.2-jre version

core/pom.xml, pom.xml
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin/pull/36
=> [MAINTENANCE] Merge master into scheduler-plugin

assemblies/cda-foundry/src/main/resources-filtered/data-integration/system/karaf/etc/custom.properties
=> [PPP-4865] - Vulnerable Component: snakeyaml

assemblies/cda-foundry/src/main/resources-filtered/data-integration/system/karaf/etc/custom.properties, pentaho/pom.xml, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pom.xml, proxy/pom.xml, proxy/src/main/java/pt/webdetails/cda/CdaUtils.java
[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

core/pom.xml, core/src/main/java/pt/webdetails/cda/endpoints/RestEndpoint.java, core/src/main/java/pt/webdetails/cda/exporter/ExportedQueryResult.java, core/src/test/java/pt/webdetails/cda/endpoints/RestEndpointTest.java, osgi/pom.xml, osgi/src/main/java/org/pentaho/ctools/cda/endpoints/CdaJettyWebSocketServlet.java, osgi/src/main/java/org/pentaho/ctools/cda/endpoints/CdaJettyWebsocket.java, osgi/src/test/java/org/pentaho/ctools/cda/endpoints/CdaJettyWebSocketServletTest.java, osgi/src/test/java/org/pentaho/ctools/cda/endpoints/CdaJettyWebsocketTest.java, pentaho/pom.xml, pentaho/src/main/java/pt/webdetails/cda/CdaUtils.java, pentaho/src/main/java/pt/webdetails/cda/cache/endpoints/CacheControllerEndpoint.java, pentaho/src/main/java/pt/webdetails/cda/cache/endpoints/CacheMonitorEndpoint.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryEndpoint.java, pentaho/src/main/java/pt/webdetails/cda/push/CdaPushQueryMessageHandler.java, pentaho/src/main/java/pt/webdetails/cda/push/PentahoEndpointConfigurationHelper.java, pentaho/src/test/java/pt/webdetails/cda/CdaUtilsTest.java, pentaho/src/test/java/pt/webdetails/cda/utils/HttpServletResponseForTests.java, pom.xml, proxy/pom.xml, proxy/src/main/java/pt/webdetails/cda/CdaUtils.java
[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE

pentaho/src/test/java/pt/webdetails/cda/utils/HttpServletResponseForTests.java
[BACKLOG-42764]-Upgrading cda from Java EE to Jakarta EE
[BACKLOG-42764]: https://hv-eng.atlassian.net/browse/BACKLOG-42764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42764]-Upgrading cda from Java EE to Jakarta EE

core/pom.xml, core/src/main/java/pt/webdetails/cda/cache/EHCacheQueryCache.java
[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

core/pom.xml
[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

assemblies/cda-foundry/src/main/resources-filtered/data-integration/system/karaf/etc/custom.properties, core/pom.xml, core/src/main/java/pt/webdetails/cda/cache/EHCacheQueryCache.java
[BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat
[BACKLOG-44915]: https://hv-eng.atlassian.net/browse/BACKLOG-44915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat
